### ISSUE TITLE
Fixed table header? 

### ISSUE THREAD

**Issue by andrei-sheina** [onechiporenko/ember-models-table#137]
How about to add fixed header, so it will stay on top when scrolling table content.

**Comment by onechiporenko** [comment]
Hi, @andrei-sheina.
I think table styling may be done outside of this addon scope.

**Comment by fenichelar** [comment]
Fixed header and footer would be really nice.

**Comment by fenichelar** [comment]
An example would really be great :)

**Comment by fenichelar** [comment]
This is what I have:

```css
.models-table-wrapper .inner-table-wrapper {
  height: calc(100vh - 200px);
  overflow: scroll;
}
```

I have 200px for the stuff above my table and the pagination bar. The problem with this is that it isn't a fixed header, just a fixed pagination bar and fixed content above the header. You can't set the `width` on a `tbody` unless the `display` is `block`. Is there a better way that I'm just not seeing?
