### ISSUE TITLE
Support custom icon classes

### ISSUE THREAD

**Issue by zavan** [onechiporenko/ember-models-table#29]
I'd like to use FontAwesome instead of Glyphicons to provide the icons, but this is not possible since icon classes are writen directly in the component template. I suggest we should be able to do something like:

```javascript
icons = {
  sortAsc: 'fa fa-sort-asc',
  sortDesc: 'fa fa-sort-desc'
}
```
```hbs
{{models-table customIcons=icons}}
```

But of course, keeping Glyphicons as the default.

**Comment by zavan** [comment]
If anyone is interested, right now I'm "aliasing" FA icons to glyphicons:

```css

span.glyphicon.glyphicon-triangle-bottom:before {
  content: "\f150";
  font-family: FontAwesome;
}

span.glyphicon.glyphicon-triangle-top:before {
  content: "\f151";
  font-family: FontAwesome;
}

span.glyphicon.glyphicon-check:before {
  content: "\f046";
  font-family: FontAwesome;
}

span.glyphicon.glyphicon-unchecked:before {
  content: "\f096";
  font-family: FontAwesome;
}

span.glyphicon.glyphicon-chevron-left:before {
  content: "\f053";
  font-family: FontAwesome;
}

span.glyphicon.glyphicon-chevron-right:before {
  content: "\f054";
  font-family: FontAwesome;
}

span.glyphicon.glyphicon-menu-left:before {
  content: "\f060";
  font-family: FontAwesome;
}

span.glyphicon.glyphicon-menu-right:before {
  content: "\f061";
  font-family: FontAwesome;
}
```

You can et the "content" unicode for the icons [here](https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss).
