### ISSUE TITLE
Scrolling options

### ISSUE THREAD

**Issue by YuliaZaiats** [onechiporenko/ember-models-table#8]
Enable horizontal scrolling (when a table is too wide to fit into a certain layout, or you have a large number of columns in the table).

**Comment by brett-anderson** [comment]
I was able to achieve this with css.
```css
.inner-table-wrapper {
  overflow-y: scroll;
  min-width: 100%;
}
```
